#!/usr/bin/env bash

sudo apt update && sudo apt upgrade -y
./run_env

#only to update environment variables
source ~/.zshrc
./run

# Run Neovim in headless mode to install plugins and tools
echo "Running Neovim to install plugins and Mason tools..."
nvim --headless +"lua require('lazy').sync(); require('mason').setup(); require('mason-tool-installer').setup(); vim.cmd('MasonToolsInstall'); vim.cmd('qa')"
echo "Neovim setup complete!"

zsh

echo "Setup complete!"

