#!/usr/bin/env bash

wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.40/quarto-1.6.40-linux-amd64.deb
sudo apt install -y ./quarto-1.6.40-linux-amd64.deb
sudo rm quarto-1.6.40-linux-amd64.deb
